name: example
description: Showcase App for Windows UI for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui:
    path: ../
  provider: ^6.1.5+1
  system_theme: ^3.1.2
  window_manager: ^0.5.0
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.3.0
  url_launcher: ^6.3.2
  clipboard: ^3.0.8
  http: ^1.6.0
  flutter_markdown_plus: ^1.0.5
  flutter_syntax_view: 
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  go_router: ^17.0.1
  intl: ^0.20.2
  google_fonts: ^6.3.3
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Segoe UI
      fonts:
        - asset: fonts/segoeuithis.ttf
        - asset: fonts/segoeuithibd.ttf
          weight: 700
        - asset: fonts/segoeuithisi.ttf
          style: italic
        - asset: fonts/segoeuithisz.ttf
          style: italic
          weight: 700

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png

flutter_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "202020"
    theme_color: "0175C2"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"