name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 3.12.0
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  recase: ^4.0.0
  scroll_pos: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl_utils: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false