name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 4.5.1
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Used on date and time pickers
  intl: '>=0.17.0 <= 1.0.0'

  # Used on TabView
  scroll_pos: ^0.4.0

  # Used on icon generator
  recase: ^4.0.0

  # Used on NumberBox
  math_expressions: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl_utils: ^2.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf
