name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 3.5.0
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf
