name: fluent_ui
description: Implements Fluent UI in Flutter. Based on the official documentation
version: 2.1.1
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  recase: any

flutter:
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf
