name: fluent_ui
description: Implements Fluent Ui in flutter. Based on the official documentation
version: 1.0.1+1
homepage: https://github.com/bdlukaa/fluent_ui

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: FluentSystemIconsP1
      fonts:
        - asset: fonts/FluentSystemIconsP1.ttf
    - family: FluentSystemIconsP2
      fonts:
        - asset: fonts/FluentSystemIconsP2.ttf
    - family: FluentSystemIconsP3
      fonts:
        - asset: fonts/FluentSystemIconsP3.ttf
    - family: FluentSystemIconsP4
      fonts:
        - asset: fonts/FluentSystemIconsP4.ttf
    - family: FluentSystemIconsP5
      fonts:
        - asset: fonts/FluentSystemIconsP5.ttf
    - family: FluentSystemIconsP6
      fonts:
        - asset: fonts/FluentSystemIconsP6.ttf
    - family: FluentSystemIconsP7
      fonts:
        - asset: fonts/FluentSystemIconsP7.ttf
