name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 4.8.7
homepage: https://bdlukaa.github.io/fluent_ui/#/
repository: https://github.com/bdlukaa/fluent_ui
issue_tracker: https://github.com/bdlukaa/fluent_ui/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - windows
  - desktop
  - ui
  - widgets

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Used on date and time pickers
  intl: '>=0.18.0 <= 1.0.0'

  # Used on TabView
  scroll_pos: '>=0.5.0 < 1.0.0'

  # Used on icon generator
  recase: ^4.1.0

  # Used on NumberBox
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  intl_utils: ^2.8.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf
